# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

let
  mkNasMount = device: {
    device = device;
    fsType = "cifs";
    options = [
      "credentials=/etc/nixos/secrets/cifs.credentials"
      "uid=1000"
      "gid=100"
      "file_mode=0644"
      "dir_mode=0755"
      "iocharset=utf8"
      "vers=3.0"
      "nosuid"
      "nodev"
      "_netdev"
      "x-systemd.idle-timeout=600"
    ];
  };
in
{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "cifs" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/710be44a-78db-4580-a2ec-61f955b7891e";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/9B11-92BE";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.graphics = {
    enable = true;
    enable32Bit = true;
  };

  # Limit's NAS
  fileSystems."/mnt/nas-misc" = mkNasMount "//nas.lcc/MAIN";
  fileSystems."/mnt/nas-ai" = mkNasMount "//nas.lcc/AI";
  fileSystems."/mnt/nas-editing" = mkNasMount "//nas.lcc/Editing";
}
